### ISSUE TITLE
mediacodec configure 报错

### ISSUE THREAD

**Issue by yanweimin7** [lakeinchina/librestreaming#105]
android.media.MediaCodec$CodecException: Error 0xffffffc3
                                                                                 at android.media.MediaCodec.native_configure(Native Method)
                                                                                 at android.media.MediaCodec.configure(MediaCodec.java:580)
                                                                                 at me.lake.librestreaming.core.RESHardVideoCore$VideoGLHandler.handleMessage(RESHardVideoCore.java:401)

**Comment by lakeinchina** [comment]
有详细点的描述么..
