### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'boolean me.lake.librestreaming.client.RESVideoClient.startStreaming(me.lake.librestreaming.rtmp.RESFlvDataCollecter)' on a null object reference

### ISSUE THREAD

**Issue by vishal02gaur** [lakeinchina/librestreaming#110]
Hi 

Some time(3 out of 10) library crashed when you start the stream..

`FATAL EXCEPTION: main
                                                                             Process: com.xxx.xxx, PID: 6903
                                                                             java.lang.NullPointerException: Attempt to invoke virtual method 'boolean me.lake.librestreaming.client.RESVideoClient.startStreaming(me.lake.librestreaming.rtmp.RESFlvDataCollecter)' on a null object reference
                                                                                 at me.lake.librestreaming.client.RESClient.startStreaming(RESClient.java:86)
                                                                                 at com.xxx.xxx.streaming2.BaseStreamingActivity.startStreaming(BaseStreamingActivity.java:276)
                                                                                 at com.xxx.xxx.streaming2.HardStreamingActivity.startBroadcast(HardStreamingActivity.java:132)
                                                                                 at com.xxx.xxx.fragment.livestream.StartupLiveStreamFragment$1.run(StartupLiveStreamFragment.java:309)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by lakeinchina** [comment]
it seems like resClient.prepare(resConfig) failed,please check it.
it appears when camera can`t create.
