### ISSUE TITLE
RtmpClient.close 闪退

### ISSUE THREAD

**Issue by guanghuili** [lakeinchina/librestreaming#135]
02-20 19:28:01.592 17691-17736/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 17736 (rtmpSender hand)
02-20 19:28:01.601 324-18052/? E/MtkOmxVenc: [0xf1fba200] FlushInputPort -> mNumPendingInput(0)
02-20 19:28:03.718 784-966/? E/NativeCrashListener: Exception dealing with report
                                                    android.system.ErrnoException: read failed: EAGAIN (Try again)
                                                        at libcore.io.Posix.readBytes(Native Method)
                                                        at libcore.io.Posix.read(Posix.java:165)
                                                        at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
                                                        at android.system.Os.read(Os.java:350)
                                                        at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:240)
                                                        at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138)

在个别cpu架构上调用RtmpClient.close会出现闪退或无响应情况？ 求解

**Comment by lakeinchina** [comment]
x86架构？

**Comment by surabhi1694** [comment]
hey i'm getting error code 9 
what should i do?

**Comment by lakeinchina** [comment]
@surabhi1694  error code9 means the tcp connection is broken , usually due to network problem
