### ISSUE TITLE
time delay

### ISSUE THREAD

**Issue by ghost** [lakeinchina/librestreaming#153]
hey i send and get live stream successfully. but when i start to get video stream it has 15 sec delay then live stream please help me how to reduce delay.?
 thank you .

**Comment by lakeinchina** [comment]
it usually cause by server or player problem,such as player buffer size.

**Comment by ghost** [comment]
hey, i'm sending one image to you. actually when the camera open it shows green line in it. what is it?how can i remove it?
![livestream](https://cloud.githubusercontent.com/assets/20115883/24537333/10d12d3e-15ff-11e7-998b-c65d31cac669.png)

**Comment by lakeinchina** [comment]
what`s your targetVideoSize?

**Comment by ghost** [comment]
res.setTargetVideoSize(new Size(1280, 720));

**Comment by lakeinchina** [comment]
that is weird.
could you print the log after "ResParameter:" ?

**Comment by ghost** [comment]
here the log i get
04-03 10:13:47.178 13208-9454/? E/ActivityManager: Sending non-protected broadcast com.motorola.motocare.INTENT_TRIGGER from system 14106:com.motorola.process.system/1000 pkg com.motorola.motgeofencesvc
                                                   java.lang.Throwable
                                                       at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:18179)
                                                       at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:18779)
                                                       at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:512)
                                                       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2905)
                                                       at android.os.Binder.execTransact(Binder.java:565)
04-03 10:13:47.313 4329-4329/me.lake.librestreaming.sample **E/hello_: testing_Log**
04-03 10:13:47.313 4329-4329/me.lake.librestreaming.sample **E/resParameters: resParameters**
04-03 10:13:47.323 12571-14049/? I/CameraService: CameraService::connect call (PID -1 "me.lake.librestreaming.sample", camera ID 1) for HAL version default and Camera API version 1
04-03 10:13:47.324 12571-14049/? I/CameraService: onTorchStatusChangedLocked: Torch status changed for cameraId=0, newStatus=0
04-03 10:13:47.328 12571-14049/? I/CameraFlashlight: Opening camera 1
04-03 10:13:47.328 12571-14049/? I/QCamera2Factory: int qcamera::QCamera2Factory::cameraDeviceOpen(int, struct hw_device_t **): Open camera id 1 API version 256
04-03 10:13:47.333 12571-14049/? I/QCamera2HWI: [KPI Perf] int qcamera::QCamera2HardwareInterface::openCamera(struct hw_device_t **): E PROFILE_OPEN_CAMERA camera id 1
04-03 10:13:47.333 12571-14049/? I/QCameraHalWatchdog: Starting Watchdog Thread...
04-03 10:13:47.334 10308-10308/? D/mm-camera: mct: mct_controller_new: Creating new mct_controller with session-id 2
04-03 10:13:47.334 10308-4392/? I/mm-camera: module_sensor_start_session:1114session 2
04-03 10:13:47.336 10308-4395/? E/mm-camera-isp2: isp_module_start_session:173 session id 2

**Comment by ghost** [comment]
hello sir, i kind of resolve this issue by changing the resolution from 720,480 to 800,480. it works fine now. but it is weird that if i set resolution to 720,480 then only i get green line other then that i am able to run with 600,480 or 800,480 etc....
