### ISSUE TITLE
Streaming Issue

### ISSUE THREAD

**Issue by PreDeToR** [lakeinchina/librestreaming#155]
Hi Guys

I am testing on a Huawei device (Huawei Mt7-L09 running andriod 4.4.2) and I get the following error:

E/ACodec: [OMX.IMG.TOPAZ.VIDEO.Encoder] configureCodec returning error -38
E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -38)
E/RESLog: ==================================
E/RESLog: RESVideoClient.start()failed
E/RESLog: java.lang.IllegalStateException
              at android.media.MediaCodec.native_configure(Native Method)
              at android.media.MediaCodec.configure(MediaCodec.java:262)
              at me.lake.librestreaming.core.RESSoftVideoCore.startStreaming(RESSoftVideoCore.java:157)
              at me.lake.librestreaming.client.RESVideoClient.startStreaming(RESVideoClient.java:194)
              at me.lake.librestreaming.client.RESClient.startStreaming(RESClient.java:86)
              at cointelvas.co.za.smartvideostreaming.StreamActivity.toggleStream(StreamActivity.java:274)
              at cointelvas.co.za.smartvideostreaming.StreamActivity.onClick(StreamActivity.java:213)
              at android.view.View.performClick(View.java:4446)
              at android.view.View$PerformClick.run(View.java:18480)
              at android.os.Handler.handleCallback(Handler.java:733)
              at android.os.Handler.dispatchMessage(Handler.java:95)
              at android.os.Looper.loop(Looper.java:136)
              at android.app.ActivityThread.main(ActivityThread.java:5314)
              at java.lang.reflect.Method.invokeNative(Native Method)
              at java.lang.reflect.Method.invoke(Method.java:515)
              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
              at dalvik.system.NativeStart.main(Native Method)
E/RESLog: -----------------------------------

Any ideas how to fix this?

**Comment by lakeinchina** [comment]
seems like mediacodec error.maybe you can try another videosize.1280*720 is usually supported.

**Comment by lakeinchina** [comment]
you can also try hard mode

**Comment by PreDeToR** [comment]
Hi 

I have tried with both 480p and 720p in my application (including RESConfig.RenderingMode.OpenGLES & NativeWindow)

I have also tried the sample application and on both soft & hard and it also generates the same error.

**Comment by lakeinchina** [comment]
sorry,I don`t hava a mate7.
it should be a device related problem.

**Comment by PreDeToR** [comment]
Hi @lakeinchina 

Any debug/info I can send you to help with checking/resolving the issue?

**Comment by lakeinchina** [comment]
sorry,but it`s hard to debug Hardware problem with log.you can try different mediacodec parameters or try another mediacodec library.
