### ISSUE TITLE
AVCProfileBaseline修改为AVCProfileMain，vivo，crash了

### ISSUE THREAD

**Issue by WangShuo1143368701** [lakeinchina/librestreaming#170]
UncaughtException detected: android.media.MediaCodec$CodecException: Error 0x80001001
                                                     at android.media.MediaCodec.native_configure(Native Method)
                                                     at android.media.MediaCodec.configure(MediaCodec.java:1791)
                                                     at me.lake.librestreaming.core.RESHardVideoCore$VideoGLHandler.handleMessage(RESHardVideoCore.java:401)

**Comment by lakeinchina** [comment]
配置这个比较麻烦，和安桌版本手机处理器都有关系，有api可以读取支持的配置。
如果解码器配置的正确应该是可以跑的，但是如果有交错编码，播放会不正常。
我在很久的dev分支里面想做mianprofile，但是大部分手机都不支持，就烂在那里不做了。
总之这个很麻烦
