### ISSUE TITLE
预览和推流分离出来？

### ISSUE THREAD

**Issue by androidwzq** [lakeinchina/librestreaming#35]
你好 如何将预览和推流分离出来？
比如我预览的时候先不推流，点击开始在推流。谢谢

**Comment by lakeinchina** [comment]
现在没这个功能，如果要加的话，不是特别容易

**Comment by androidwzq** [comment]
嗯 目前能预览注释掉rtmpSender.start()。
然后要推流直播先stop 再start。不过会卡一下，体验不好。

**Comment by skybdemq** [comment]
我也要做这个，预览与推流分离是基本需求。
在软编模式，我通过提取RESSoftVideoCore类start方法videoFilterHandlerThread初始化代码加在自已定义的startPreview方法实现，但硬编太复杂，无从下手。
用预览注释掉rtmpSender.start()方法，硬编推流出报错，软编推流成功

**Comment by flyminiboy** [comment]
你们分离开了吗?

**Comment by lakeinchina** [comment]
这个特性在dev_split_preview_stream分支，hard已经分开，现在还有bug

**Comment by flyminiboy** [comment]
使用分离的分支 每次 stop 的时候都奔溃
java.lang.RuntimeException: eglSwapBuffers,failed!
                                                                                 at me.lake.librestreaming.core.RESHardVideoCore$VideoGLHandler.drawMediaCodec(RESHardVideoCore.java:387)
                                                                                 at me.lake.librestreaming.core.RESHardVideoCore$VideoGLHandler.drawFrame(RESHardVideoCore.java:302)
                                                                                 at me.lake.librestreaming.core.RESHardVideoCore$VideoGLHandler.handleMessage(RESHardVideoCore.java:266)
