### ISSUE TITLE
乐视Max2 打开摄像头报异常

### ISSUE THREAD

**Issue by nilvxingren** [lakeinchina/librestreaming#54]
```
08-20 21:34:01.714 7198-7198/me.lake.librestreaming.sample I/ActivityThreadEui: Handling launch of ActivityRecord{5ef5544 token=android.os.BinderProxy@97a362d {me.lake.librestreaming.sample/me.lake.librestreaming.sample.HardStreamingActivity}} startsNotResumed=false
08-20 21:34:01.802 7198-7198/me.lake.librestreaming.sample W/CameraBase: An error occurred while connecting to camera: 1
08-20 21:34:01.803 7198-7198/me.lake.librestreaming.sample E/RESLog: ==================================
08-20 21:34:01.803 7198-7198/me.lake.librestreaming.sample E/RESLog: camera.open()failed
08-20 21:34:01.803 7198-7198/me.lake.librestreaming.sample E/RESLog: java.lang.RuntimeException: Fail to connect to camera service
                                                                         at android.hardware.Camera.<init>(Camera.java:531)
                                                                         at android.hardware.Camera.open(Camera.java:373)
                                                                         at me.lake.librestreaming.client.RESVideoClient.createCamera(RESVideoClient.java:85)
                                                                         at me.lake.librestreaming.client.RESVideoClient.prepare(RESVideoClient.java:48)
                                                                         at me.lake.librestreaming.client.RESClient.prepare(RESClient.java:52)
                                                                         at me.lake.librestreaming.sample.BaseStreamingActivity.onCreate(BaseStreamingActivity.java:102)
                                                                         at me.lake.librestreaming.sample.HardStreamingActivity.onCreate(HardStreamingActivity.java:56)
                                                                         at android.app.Activity.performCreate(Activity.java:6321)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2418)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2527)
                                                                         at android.app.ActivityThread.access$1100(ActivityThread.java:154)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5568)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-20 21:34:01.803 7198-7198/me.lake.librestreaming.sample E/RESLog: -----------------------------------
08-20 21:34:01.803 7198-7198/me.lake.librestreaming.sample E/RESLog: can not open camera
08-20 21:34:01.804 7198-7198/me.lake.librestreaming.sample E/RES: prepare,failed!!
```

**Comment by nilvxingren** [comment]
原因找到了 需要在 Settings -> Apps -> [YourApp] -> Permissions  设置一下 但是现在点击之后黑屏了，日志都没有

**Comment by lakeinchina** [comment]
右上角的信息显示什么?

**Comment by nilvxingren** [comment]
当时没注意，后来重启了一下就好了，可能是另外一个应用 导致的
