### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'boolean me.lake.librestreaming.client.RESVideoClient.stopPreview()' on a null object reference

### ISSUE THREAD

**Issue by vishal02gaur** [lakeinchina/librestreaming#58]
```
App crashing while closing activity happen some time
                                                                           --------- beginning of crash
```

08-26 22:03:04.487 10802-10802/me.lake.librestreaming.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: me.lake.librestreaming.sample, PID: 10802
                                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'boolean me.lake.librestreaming.client.RESVideoClient.stopPreview()' on a null object reference
                                                                                   at me.lake.librestreaming.client.RESClient.stopPreview(RESClient.java:133)
                                                                                   at me.lake.librestreaming.sample.BaseStreamingActivity$override.onSurfaceTextureDestroyed(BaseStreamingActivity.java:252)
                                                                                   at me.lake.librestreaming.sample.BaseStreamingActivity$override.access$dispatch(BaseStreamingActivity.java)
                                                                                   at me.lake.librestreaming.sample.BaseStreamingActivity.onSurfaceTextureDestroyed(BaseStreamingActivity.java:0)
                                                                                   at android.view.TextureView.destroySurface(TextureView.java:237)
                                                                                   at android.view.TextureView.onDetachedFromWindowInternal(TextureView.java:227)
                                                                                   at android.view.View.dispatchDetachedFromWindow(View.java:14578)
                                                                                   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3065)
                                                                                   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3065)
                                                                                   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3065)
                                                                                   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3065)
                                                                                   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3065)
                                                                                   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3065)
                                                                                   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3065)
                                                                                   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3065)
                                                                                   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3065)
                                                                                   at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3080)
                                                                                   at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5618)
                                                                                   at android.view.ViewRootImpl.die(ViewRootImpl.java:5595)
                                                                                   at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:397)
                                                                                   at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:352)
                                                                                   at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
                                                                                   at android.app.ActivityThread.cleanUpPendingRemoveWindows(ActivityThread.java:3133)
                                                                                   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3200)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
                                                                                   at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4098)
                                                                                   at android.app.ActivityThread.-wrap15(ActivityThread.java)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1360)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by lakeinchina** [comment]
soft or hard mode？did you change anything?
